Repository eduNEXT/tvm, pull requests merged in 2022-10, with the labels that each got.

#54 docs: add the base doc configuration DS-243
  .readthedocs.yml
  Makefile
  docs/Makefile
  docs/make.bat
  docs/source/_static/.gitkeep
  docs/source/_static/Knowledge_Base_logo.png
  docs/source/_static/_js/custom.js
  docs/source/_static/css/custom.css
  docs/source/_static/logo_smaller.png
  docs/source/conf.py
  docs/source/index.rst
  requirements/base.txt
  requirements/constraints.txt
  requirements/dev.txt
  requirements/doc.in
  requirements/doc.txt
  requirements/pip.txt
Labels: size/l

#55 feat: add tvm documentation DS-243
  docs/TutorEnvironmentManager.rst
  docs/TutorVersionManager.rst
  docs/source/index.rst
  docs/source/tvm_advanced_information.rst
  docs/source/tvm_how_to_guides/how_to_configure_vars.rst
  docs/source/tvm_how_to_guides/index.rst
  docs/source/tvm_quickstart.rst
  docs/source/tvm_topic_guides/environment_manager.rst
  docs/source/tvm_topic_guides/index.rst
  docs/source/tvm_topic_guides/version_manager.rst
  docs/source/tvm_tutorials/creating_two_dev_env.rst
  docs/source/tvm_tutorials/index.rst
Labels: size/l

#58 fix(DS-291): create a project with a version that is not install
  .github/pull_request_template.md
  docs/source/tvm_quickstart.rst
  docs/source/tvm_topic_guides/environment_manager.rst
  docs/source/tvm_tutorials/creating_two_dev_env.rst
  tvm/cli.py
Labels: size/m

#59 docs: update tvm doc release version
  .github/pull_request_template.md
  docs/source/conf.py
Labels: size/s
