Repository eduNEXT/tvm, pull requests merged in 2022-08, with the labels that each got.

#37 fix: remove requests cache
  requirements/base.in
  requirements/base.txt
  requirements/dev.in
  requirements/dev.txt
  requirements/pip-tools.txt
  requirements/pip.txt
  tvm/version_manager/infrastructure/version_manager_git_repository.py
Labels: bug

#38 fix: solve issue with names that contains hyphen and underscore
  tvm/environment_manager/application/tutor_project_creator.py
  tvm/environment_manager/domain/environment_manager_repository.py
  tvm/environment_manager/domain/project_name.py
  tvm/environment_manager/infrastructure/environment_manager_git_repository.py
Labels: bug

#39 docs: organize tvm documentation
  .gitignore
  README.md
  docs/TutorEnvironmentManager.rst
  docs/TutorVersionManager.rst
  docs/images/tvm_list.png
  docs/images/tvm_list_project.png
  docs/images/tvm_plugins_list.png
Labels: documentation

#43 fix: add virtualenv to requirements and upgrade
  requirements/base.in
  requirements/base.txt
  requirements/dev.txt
  requirements/pip.txt
Labels: hotfix

#45 Hpg/bumpversion to v2.0.1
  CHANGELOG.md
  setup.cfg
  tvm/__init__.py
Labels: hotfix
