Repository eduNEXT/tvm, pull requests merged in 2022-05, with the labels that each got.

#1 Fmo/publishing
  CHANGELOG.md
  Makefile
  README.md
  stack/cli.py
Labels: bug, hotfix

#2 docs: update LICENSE
  LICENSE
  LICENSE.txt
  README.md
Labels: documentation, help wanted

#6 fix: remove all relations with stack and strains
  .coveragerc
  Makefile
  setup.cfg
  setup.py
  stack/cli.py
  stack/config.py
  stack/tests/__init__.py
  stack/tests/test_cli.py
  stack/tests/test_config.py
  stack/tests/test_tvm.py
  tests/test_cli.py
  tvm/__init__.py
  tvm/cli.py
  tvm/templates/__init__.py
  tvm/templates/tutor_switcher.py
Labels: bug, hotfix

#7 docs: update README
  README.md
Labels: documentation

#3 docs: update issue templates and add contributing file
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/issue_assignment.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#9 fix: solve issue with setup command
  tvm/cli.py
Labels: bug, help wanted, hotfix

#15 fix: solve bug with tvm project env
  tvm/templates/tvm_activate.py
Labels: bug

#16 feat: add command tvm plugins install
  tvm/cli.py
  tvm/templates/tvm_activate.py
Labels: bug, enhancement

#17 docs: update README
  README.md
Labels: documentation

#19 feat: add tvm config commands
  README.md
  tvm/cli.py
  tvm/templates/tutor_switcher.py
Labels: enhancement

#22 feat: add plugins uninstall command
  tvm/cli.py
Labels: enhancement

#24 chore: add bumpversion settings and update setup info
  setup.cfg
  setup.py
Labels: documentation, enhancement
